// <auto-generated />
using System;
using FoodSafetyInspectionTracker.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FoodSafetyInspectionTracker.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("FoodSafetyInspectionTracker.Models.FollowUp", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime?>("ClosedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("InspectionId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("InspectionId");

                    b.ToTable("FollowUps");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DueDate = new DateTime(2026, 1, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            InspectionId = 3,
                            Status = 0
                        },
                        new
                        {
                            Id = 2,
                            ClosedDate = new DateTime(2026, 1, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DueDate = new DateTime(2026, 1, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            InspectionId = 5,
                            Status = 1
                        },
                        new
                        {
                            Id = 3,
                            DueDate = new DateTime(2026, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            InspectionId = 7,
                            Status = 0
                        },
                        new
                        {
                            Id = 4,
                            ClosedDate = new DateTime(2026, 2, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DueDate = new DateTime(2026, 2, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            InspectionId = 11,
                            Status = 1
                        },
                        new
                        {
                            Id = 5,
                            DueDate = new DateTime(2026, 2, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            InspectionId = 14,
                            Status = 0
                        },
                        new
                        {
                            Id = 6,
                            DueDate = new DateTime(2026, 2, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            InspectionId = 15,
                            Status = 0
                        },
                        new
                        {
                            Id = 7,
                            ClosedDate = new DateTime(2026, 2, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DueDate = new DateTime(2026, 2, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            InspectionId = 17,
                            Status = 1
                        },
                        new
                        {
                            Id = 8,
                            DueDate = new DateTime(2026, 2, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            InspectionId = 20,
                            Status = 0
                        },
                        new
                        {
                            Id = 9,
                            DueDate = new DateTime(2026, 2, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            InspectionId = 22,
                            Status = 0
                        },
                        new
                        {
                            Id = 10,
                            DueDate = new DateTime(2026, 2, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            InspectionId = 25,
                            Status = 0
                        });
                });

            modelBuilder.Entity("FoodSafetyInspectionTracker.Models.Inspection", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("InspectionDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<int>("Outcome")
                        .HasColumnType("int");

                    b.Property<int>("PremisesId")
                        .HasColumnType("int");

                    b.Property<int>("Score")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PremisesId");

                    b.ToTable("Inspections");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            InspectionDate = new DateTime(2026, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Notes = "Good hygiene.",
                            Outcome = 0,
                            PremisesId = 1,
                            Score = 92
                        },
                        new
                        {
                            Id = 2,
                            InspectionDate = new DateTime(2026, 1, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Notes = "Minor improvements needed.",
                            Outcome = 0,
                            PremisesId = 2,
                            Score = 71
                        },
                        new
                        {
                            Id = 3,
                            InspectionDate = new DateTime(2026, 1, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Notes = "Storage issue.",
                            Outcome = 1,
                            PremisesId = 3,
                            Score = 49
                        },
                        new
                        {
                            Id = 4,
                            InspectionDate = new DateTime(2026, 1, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Notes = "Compliant.",
                            Outcome = 0,
                            PremisesId = 4,
                            Score = 80
                        },
                        new
                        {
                            Id = 5,
                            InspectionDate = new DateTime(2026, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Notes = "Cross contamination controls weak.",
                            Outcome = 1,
                            PremisesId = 5,
                            Score = 55
                        },
                        new
                        {
                            Id = 6,
                            InspectionDate = new DateTime(2026, 1, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Notes = "Solid process.",
                            Outcome = 0,
                            PremisesId = 6,
                            Score = 88
                        },
                        new
                        {
                            Id = 7,
                            InspectionDate = new DateTime(2026, 1, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Notes = "Temperature log missing.",
                            Outcome = 1,
                            PremisesId = 7,
                            Score = 64
                        },
                        new
                        {
                            Id = 8,
                            InspectionDate = new DateTime(2026, 1, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Notes = "Adequate.",
                            Outcome = 0,
                            PremisesId = 8,
                            Score = 76
                        },
                        new
                        {
                            Id = 9,
                            InspectionDate = new DateTime(2026, 1, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Notes = "Very clean.",
                            Outcome = 0,
                            PremisesId = 9,
                            Score = 91
                        },
                        new
                        {
                            Id = 10,
                            InspectionDate = new DateTime(2026, 1, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Notes = "Training reminder.",
                            Outcome = 0,
                            PremisesId = 10,
                            Score = 70
                        },
                        new
                        {
                            Id = 11,
                            InspectionDate = new DateTime(2026, 1, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Notes = "Pest control action required.",
                            Outcome = 1,
                            PremisesId = 11,
                            Score = 45
                        },
                        new
                        {
                            Id = 12,
                            InspectionDate = new DateTime(2026, 1, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Notes = "Good standard.",
                            Outcome = 0,
                            PremisesId = 12,
                            Score = 86
                        },
                        new
                        {
                            Id = 13,
                            InspectionDate = new DateTime(2026, 2, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Notes = "Routine check.",
                            Outcome = 0,
                            PremisesId = 1,
                            Score = 90
                        },
                        new
                        {
                            Id = 14,
                            InspectionDate = new DateTime(2026, 2, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Notes = "Cleanliness issue.",
                            Outcome = 1,
                            PremisesId = 2,
                            Score = 52
                        },
                        new
                        {
                            Id = 15,
                            InspectionDate = new DateTime(2026, 2, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Notes = "Record keeping poor.",
                            Outcome = 1,
                            PremisesId = 3,
                            Score = 61
                        },
                        new
                        {
                            Id = 16,
                            InspectionDate = new DateTime(2026, 2, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Notes = "Improved.",
                            Outcome = 0,
                            PremisesId = 4,
                            Score = 82
                        },
                        new
                        {
                            Id = 17,
                            InspectionDate = new DateTime(2026, 2, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Notes = "Equipment sanitization required.",
                            Outcome = 1,
                            PremisesId = 5,
                            Score = 59
                        },
                        new
                        {
                            Id = 18,
                            InspectionDate = new DateTime(2026, 2, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Notes = "Satisfactory.",
                            Outcome = 0,
                            PremisesId = 6,
                            Score = 84
                        },
                        new
                        {
                            Id = 19,
                            InspectionDate = new DateTime(2026, 2, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Notes = "Minor notes.",
                            Outcome = 0,
                            PremisesId = 7,
                            Score = 79
                        },
                        new
                        {
                            Id = 20,
                            InspectionDate = new DateTime(2026, 2, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Notes = "Cleaning schedule not followed.",
                            Outcome = 1,
                            PremisesId = 8,
                            Score = 47
                        },
                        new
                        {
                            Id = 21,
                            InspectionDate = new DateTime(2026, 2, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Notes = "Excellent.",
                            Outcome = 0,
                            PremisesId = 9,
                            Score = 94
                        },
                        new
                        {
                            Id = 22,
                            InspectionDate = new DateTime(2026, 2, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Notes = "Food storage issue.",
                            Outcome = 1,
                            PremisesId = 10,
                            Score = 66
                        },
                        new
                        {
                            Id = 23,
                            InspectionDate = new DateTime(2026, 2, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Notes = "Corrective actions in place.",
                            Outcome = 0,
                            PremisesId = 11,
                            Score = 74
                        },
                        new
                        {
                            Id = 24,
                            InspectionDate = new DateTime(2026, 2, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Notes = "Good condition.",
                            Outcome = 0,
                            PremisesId = 12,
                            Score = 83
                        },
                        new
                        {
                            Id = 25,
                            InspectionDate = new DateTime(2026, 2, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Notes = "Staff hygiene retraining.",
                            Outcome = 1,
                            PremisesId = 5,
                            Score = 69
                        });
                });

            modelBuilder.Entity("FoodSafetyInspectionTracker.Models.Premises", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)");

                    b.Property<int>("RiskRating")
                        .HasColumnType("int");

                    b.Property<string>("Town")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)");

                    b.HasKey("Id");

                    b.ToTable("Premises");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "10 Dock Lane",
                            Name = "Harbour Deli",
                            RiskRating = 0,
                            Town = "Riverton"
                        },
                        new
                        {
                            Id = 2,
                            Address = "22 Market St",
                            Name = "Town Bakery",
                            RiskRating = 1,
                            Town = "Riverton"
                        },
                        new
                        {
                            Id = 3,
                            Address = "8 Green Rd",
                            Name = "Sunrise Cafe",
                            RiskRating = 2,
                            Town = "Riverton"
                        },
                        new
                        {
                            Id = 4,
                            Address = "14 Hill Ave",
                            Name = "North Grill",
                            RiskRating = 1,
                            Town = "Oakford"
                        },
                        new
                        {
                            Id = 5,
                            Address = "2 River Walk",
                            Name = "Oakford Sushi",
                            RiskRating = 2,
                            Town = "Oakford"
                        },
                        new
                        {
                            Id = 6,
                            Address = "40 Cedar Dr",
                            Name = "Family Pizza",
                            RiskRating = 0,
                            Town = "Oakford"
                        },
                        new
                        {
                            Id = 7,
                            Address = "7 Lake View",
                            Name = "Meadow Bistro",
                            RiskRating = 1,
                            Town = "Kingswell"
                        },
                        new
                        {
                            Id = 8,
                            Address = "18 Mill Road",
                            Name = "Kingswell Tacos",
                            RiskRating = 2,
                            Town = "Kingswell"
                        },
                        new
                        {
                            Id = 9,
                            Address = "31 Station Rd",
                            Name = "Noodle House",
                            RiskRating = 0,
                            Town = "Kingswell"
                        },
                        new
                        {
                            Id = 10,
                            Address = "9 Orchard Way",
                            Name = "Garden Eatery",
                            RiskRating = 1,
                            Town = "Riverton"
                        },
                        new
                        {
                            Id = 11,
                            Address = "5 Quay St",
                            Name = "Riverside Pub",
                            RiskRating = 2,
                            Town = "Oakford"
                        },
                        new
                        {
                            Id = 12,
                            Address = "1 College Green",
                            Name = "Campus Canteen",
                            RiskRating = 1,
                            Town = "Kingswell"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("ClaimType")
                        .HasColumnType("longtext");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("longtext");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("longtext");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetime");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("longtext");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("longtext");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("longtext");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("ClaimType")
                        .HasColumnType("longtext");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("longtext");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("longtext");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("RoleId")
                        .HasColumnType("varchar(255)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("longtext");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("FoodSafetyInspectionTracker.Models.FollowUp", b =>
                {
                    b.HasOne("FoodSafetyInspectionTracker.Models.Inspection", "Inspection")
                        .WithMany("FollowUps")
                        .HasForeignKey("InspectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Inspection");
                });

            modelBuilder.Entity("FoodSafetyInspectionTracker.Models.Inspection", b =>
                {
                    b.HasOne("FoodSafetyInspectionTracker.Models.Premises", "Premises")
                        .WithMany("Inspections")
                        .HasForeignKey("PremisesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Premises");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FoodSafetyInspectionTracker.Models.Inspection", b =>
                {
                    b.Navigation("FollowUps");
                });

            modelBuilder.Entity("FoodSafetyInspectionTracker.Models.Premises", b =>
                {
                    b.Navigation("Inspections");
                });
#pragma warning restore 612, 618
        }
    }
}
